### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ArsHaider** [cloud-gov/cg-manage-rds#22]
We have had multiple customers attempting to utilize the cg-manage-rds tool to access and download the data in their database. Unfortunately they have been received a FileNotFoundError.

## Notes
2 customers experiencing this issue were using Macs running Mac OS Sonoma. One customer was using PostgreSQL, another was using MySQL. A screenshot of the error is noted below.

<img width="782" alt="FileNotFoundError" src="https://github.com/cloud-gov/cg-manage-rds/assets/104385372/beb50af5-7c7f-41e6-b331-40a8c1de4c0c">

## Acceptance Criteria
Will investigate the issue to determine the cause and work towards a solution for the issue.

-Test cg-manage-rds to see if the matter can be replicated
-Identify if the specific error is replicated
-Work towards a solution for that specific error or determine if it is a broader issue that needs further investigation and resolution.

**Comment by markdboyd** [comment]
The problem is that the template for the Homebrew formula hardcodes the dependencies and it only includes `click` and not `semver`: https://github.com/cloud-gov/homebrew-cloudgov/blob/main/Versions/cg-manage-rds/cg-manage-rds.tmpl

I need to see if we can make this formula template update automatically

**Comment by markdboyd** [comment]
We have verified that the cg-manage-rds package now works correctly when installed from Homebrew, so this ticket is complete
